name: main

on:
  pull_request:
    branches:
    - main
    
    
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
          
      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: test 
          
      - name: Check types
        uses: borales/actions/yarn@v4
        with:
          cmd: check-types
          
      - name: Run test 
        uses: borales/actions-yarn@v4
        with:
          cmd: test
          dir: 'frontend' 
        
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build 